services:
  caddy:
    image: ${CADDY_IMAGE:-lucaslorentz/caddy-docker-proxy:latest-alpine}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      - ${CADDY_INGRESS_NETWORKS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CADDY_VOLUME}:/data
    networks:
      - caddy-net
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:2019/metrics || exit 1"]
      start_period: 20s
      interval: 20s
      timeout: 5s
      retries: 3

networks:
  caddy-net:
    name: caddy-net
